### ISSUE TITLE
Client page not working

### ISSUE THREAD

**Issue by alvaropietrobono** [streamingriver/setup-sr#3]
Client page not working:
HTTP ERROR 500

Setup went good on fresh Centos7
The only error marked as "fine" are below:

TASK [Create SR Database ( errors are fine here )] ***********************************************************************************************************
failed: [incredbl13] (item=/var/www/sr/migrations/03-updates.sql) => {"ansible_loop_var": "item", "changed": false, "item": "/var/www/sr/migrations/03-updates.sql", "msg": "ERROR 1146 (42S02) at line 1: Table 'sriptvdb.clients' doesn't exist\n"}
failed: [incredbl13] (item=/var/www/sr/migrations/02-update.sql) => {"ansible_loop_var": "item", "changed": false, "item": "/var/www/sr/migrations/02-update.sql", "msg": "ERROR 1146 (42S02) at line 1: Table 'sriptvdb.channels' doesn't exist\n"}
changed: [incredbl13] => (item=/var/www/sr/migrations/01-main.sql) 

TASK [Check if firewalld is on (Errors are fine here)] *******************************************************************************************************
fatal: [incredbl13]: FAILED! => {"changed": true, "cmd": ["/bin/systemctl", "-q", "is-enabled", "firewalld"], "delta": "0:00:00.019241", "end": "2019-11-04 11:15:45.339533", "msg": "non-zero return code", "rc": 1, "start": "2019-11-04 11:15:45.320292", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

**Comment by blinkinglight** [comment]
i have added to setup-sr/setup_mysql.sh because sometimes automated setup fails. run it manualy if client page doesnt work.
